version: '3.4'

services:

  headnode:
    container_name: headnode
    build: ./headnode
    expose: 
      - "5000"
    depends_on:
      - datanode1
      - datanode2
      - datanode3
    volumes:
      - ./headnode:/usr/bin/archivos

  datanode1:
    container_name: datanode1
    build: ./datanode1
    expose: 
      - "8001"
    volumes:
      - ./datanode1:/usr/bin/archivos

  datanode2:
    container_name: datanode2
    build: ./datanode2
    expose: 
      - "8002"
    volumes:
      - datanode2:/usr/bin/archivos

  datanode3:
    container_name: datanode3
    build: ./datanode3
    expose: 
      - "8003"
    volumes:
      - ./datanode3:/usr/bin/archivos
  
  client:
    container_name: client
    build: ./cliente
    depends_on:
      - headnode
    volumes:
      - ./cliente:/usr/bin/archivos
  
volumes:
  headnode:
  datanode1:
  datanode2:
  datanode3:
  client:

