version: '3.4'

services:

  headnode:
    container_name: headnode
    build: ./headnode
    expose: 
      - "5000"
    depends_on:
      - datanode1
      - datanode2
      - datanode3

  datanode1:
    container_name: datanode1
    build: ./datanode1
    expose: 
      - "8001"

  datanode2:
    container_name: datanode2
    build: ./datanode2
    expose: 
      - "8002"

  datanode3:
    container_name: datanode3
    build: ./datanode3
    expose: 
      - "8003"
  
  client:
    container_name: client
    build: ./cliente
    depends_on:
      - headnode
  


