version: '3.4'

services:

  headnode:
    container_name: headnode
    build: ./headnode
    expose: 
      - "5000"
    depends_on:
      - datanode1
      - datanode2
      - datanode3
    volumes:
      - ./headnode/archivos:/archivos
    privileged: true
    
  datanode1:
    container_name: datanode1
    build: ./datanode1
    expose: 
      - "8001"
    volumes:
      - ./datanode1/archivos:/archivos
    privileged: true

  datanode2:
    container_name: datanode2
    build: ./datanode2
    expose: 
      - "8002"
    volumes:
      - ./datanode2/archivos:/archivos
    privileged: true
    
  datanode3:
    container_name: datanode3
    build: ./datanode3
    expose: 
      - "8003"
    volumes:
      - ./datanode3/archivos:/archivos
    privileged: true
    
  client:
    container_name: client
    build: ./client
    depends_on:
      - headnode
    volumes:
      - ./client/archivos:/archivos
    privileged: true
  

